version: '3.8'

services:
  web:
    build: .
    ports:
      - "5000:5000"
    depends_on:
      - db
    environment:
      - DATABASE_URL=mysql://root:26729325@db:3306/webTest
    volumes:
      - .:/app
    
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: 26729325
      MYSQL_DATABASE: webTest
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data: